nameOverride: "redbank-playground"

env:
  ORCHESTRATOR_URL: ""
  KEYCLOAK_URL: "https://keycloak-keycloak.apps.rosa.redbank-demo2.ij5f.p3.openshiftapps.com"
  KEYCLOAK_REALM: "redbank"
  KEYCLOAK_CLIENT_ID: "redbank-mcp"
